In [1]:
import pandas as pd
import io
import requests
import numpy as np
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import get_file
import matplotlib.pyplot as plt
from matplotlib.pyplot import *
from scipy.stats import zscore
import logictensornetworks as ltn

In [2]:
a = ltn.Constant(1, trainable = False) #tensor de ordinul 1
x = ltn.Constant([2,3], trainable = False) #tensor de ordinul 2
y = ltn.Constant([[1,2,3],[4,5,6]], trainable = False) #tensor de ordinul 3
z = ltn.Constant([[1,2,3],[4,5,6],[7,8,9]], trainable = True) # tensor de ordinul 4
print(a)
print(z.tensor)

Metal device set to: Apple M1
ltn.Constant(tensor=[1.], trainable=False, free_vars=[])
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>


2022-04-02 18:01:48.168403: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-04-02 18:01:48.168732: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [63]:
class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.dense_layer1 = tf.keras.layers.Dense(20, activation=tf.nn.relu)
        self.dense_layer2 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense_layer3 = tf.keras.layers.Dense(1, activation = tf.nn.sigmoid)
    def call(self, x, y):
        x=self.dense_layer1(x)
        y=self.dense_layer2(x)
        return self.dense_layer3(y)

model = Model()
Pred1 = ltn.Predicate(model)

const = ltn.Constant([1,2,3], trainable = False)
x = tf.constant([2,3])
Pred2 = ltn.Predicate.Lambda(lambda var: tf.exp(-tf.norm(var-1,axis=1)))

In [64]:
print(Pred2(const))

ltn.Formula(tensor=0.10687792301177979, free_vars=[])


In [77]:
v = ltn.Variable('v',np.random.normal(0.,1.,(5,5)))
va = ltn.Variable('va',np.random.normal(0.,2.,(3,5)))
print(v)

ltn.Variable(label=v, tensor=[[-0.43627578 -0.2976437  -2.4928448   1.1746471   2.2041492 ]
 [ 0.4056408   0.9638937  -1.5063173  -0.2246969  -0.20277514]
 [-1.3031697  -0.6009085   2.176373    0.33341274 -0.38255623]
 [-0.97398514  0.47645572  0.5281652   1.1575196   0.24908398]
 [ 0.38763118 -0.8616349   0.18741466 -0.14276373 -0.29453826]], free_vars=['v'])


In [78]:
Not = ltn.Wrapper_Connective(ltn.fuzzy_ops.Not_Std())
And = ltn.Wrapper_Connective(ltn.fuzzy_ops.And_Prod())
Or = ltn.Wrapper_Connective(ltn.fuzzy_ops.Or_ProbSum())
Implies = ltn.Wrapper_Connective(ltn.fuzzy_ops.Implies_Reichenbach())
Equiv = ltn.Wrapper_Connective(ltn.fuzzy_ops.Equiv(ltn.fuzzy_ops.And_Prod(),ltn.fuzzy_ops.Implies_Reichenbach()))
Forall = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMeanError(p=4),semantics="forall")
Exists = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMean(p=6),semantics="exists")

In [91]:
x = ltn.Constant([2.,3., 5.1, 4.3], trainable = False) #tensor de ordinul 2
y = ltn.Constant([2.,3., 4.1, 4.3], trainable = False) #tensor de ordinul 2
Eq = ltn.Predicate.Lambda(lambda args: tf.exp(-tf.norm(args[0]-args[1],axis=1))) # predicate measuring similarity
print(Eq([x,y]))
print(Not(Eq([x,y])))
print(And(Eq([x,y]), Eq([x,y])))
print(Or(Eq([x,y]), Eq([x,y])))
print(Implies(Eq([x,y]), Eq([x,y])))

ltn.Formula(tensor=0.3678794205188751, free_vars=[])
ltn.Formula(tensor=0.6321206092834473, free_vars=[])
ltn.Formula(tensor=0.1353817582130432, free_vars=[])
ltn.Formula(tensor=0.6003770232200623, free_vars=[])
ltn.Formula(tensor=0.7674024105072021, free_vars=[])
